# Generated by Django 2.0 on 2018-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='folder_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
