# Generated by Django 2.0 on 2018-02-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_memory_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
