# Generated by Django 2.0 on 2018-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_sharedtimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtimeline',
            name='permission_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sharedtimeline',
            name='permission',
            field=models.CharField(default='reader', max_length=10),
        ),
    ]
