# Generated by Django 2.0 on 2018-02-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Card'),
        ),
    ]
