# Generated by Django 2.0 on 2018-02-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20180201_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
