# Generated by Django 2.0 on 2018-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20180201_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='file_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
