# Generated by Django 2.0 on 2018-02-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20180201_1547'),
        ('timeline', '0007_memory_name'),
    ]

    operations = [
    ]
