# Generated by Django 2.0 on 2018-03-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20180323_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='latitutde',
            new_name='latitude',
        ),
    ]
