# Generated by Django 2.0 on 2018-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_merge_20180201_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
