# Generated by Django 2.0 on 2018-04-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_group_userhasgroup'),
        ('timeline', '0008_auto_20180323_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHasTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(default='reader', max_length=10)),
                ('active', models.SmallIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline')),
            ],
        ),
    ]
